# Default configuration
#
# To override these values, multiple options:
# - Environment variable:
#     DB__REDIS_URL="redis://localhost:6379" npm start
# - Arguments:
#     npm start -- --db:redis_url "redis://localhost:6379"
# - .moniteurrc.yml (override file):
#     copy and paste the contents of this file to .moniteurrc.yml
#     and tweak the values as desired

# assets:
  # FT desktop CSS bundle:
  #   - "http://s1.ft-static.com/m/style/90975546/bundles/core.css"
  #   - "http://navigation.webservices.ft.com/v1/navigation/ft/css/style.min.css"
  #   - "http://s1.ft-static.com/m/style/5c37627a/bundles/nonArticle.css"
  # Guardian's CSS:
  #   - "http://assets.guim.co.uk/stylesheets/global.css"
  #   - "http://assets.guim.co.uk/stylesheets/head.default.css"
  # Main CSS: "fixtures/main.css"
  # Another CSS: "fixtures/main2.css"
  # ABC Script: "fixtures/abc.js"
  # My XYZ Script: "fixtures/xyz.js"
  # My Bundle of Scripts:
  #   - "fixtures/abc.js"
  #   - "fixtures/xyz.js"
  # A remote Script: "http://assets.guim.co.uk/javascripts/bootstraps/app.js"
  # A website: "http://www.theguardian.com"
db:
  directory: ".moniteurdb"
