# Default configuration
#
# To override these values, multiple options:
# - Environment variable:
#     DB__REDIS_URL="redis://localhost:6379" npm start
# - Arguments:
#     npm start -- --db:redis_url "redis://localhost:6379"
# - .moniteurrc.yml (override file):
#     copy and paste the contents of this file to .moniteurrc.yml
#     and tweak the values as desired
db:
  directory: ".moniteurdb"
